### ISSUE TITLE
[doc] Broken link capital-ctf.com

### ISSUE THREAD

**Issue by ShahriyarR** [Checkmarx/capital#70]
Visit [capital-ctf.com](https://www.capital-ctf.com/) to learn about the vulnerabilities and the challenges.

The link in the README seems to be broken.

From where to get the CTF challenges/descriptions?

**Comment by liadlevy** [comment]
The website was designed for the Blackhat event. If you're interested in playing the CTF, you can either execute `docker-compose up -d` or setup from the source code. This will allow you to play the CTF locally on your own machine.

**Comment by ErezYalon** [comment]
#72
